### ISSUE TITLE
Total Customer indebtedness (Outstanding all unpaid balances )

### ISSUE THREAD

**Issue by maikant** [geelus/New-Geelus#1]
There is need to have a tag for all unpaid outstanding balances for customers
i.e for all transactions that have not been paid(collected items + uncollected items + items in processing stage)

The tag will be needed incase you want to remind customers on text messages, receipt and email for outstanding balances which might be due to some customers collecting items without paying, this mostly happens in countries in africa and countries like india, pakistan, srilanka etc

My email: ahmedee2002@gmail.com

**Comment by MarkJeoffery** [comment]
The general workflow of Geelus is:
1- Place the order
2- Mark done
3- Mark collected (which will direct you to payment page if not paid). 

Any transaction which is not done, paid or collected before the "Due date" is called "Overdue" which can be accessed in transaction history when you click on "Overdue" button.

If your intention of the tag is to know what customers have not paid and then send them SMS or email, the easiest way is to use the account receivables report found under "Reports -> Customers -> Customer accounts". Through this simple report, you can get all the orders by customers Unpaid (or even paid). Clicking on the "Outstanding column" will sort the data by outstanding amount which allows you to see the highest amount outstanding first. 

Clicking each column will drill down to the detailed transactions which allows you to send an email or SMS to customers to let them know they owe you.

**Comment by geelus** [comment]
Answer above is the designated way to handle outstanding orders.
